from enum import Enum


class TechStack(Enum):
  REACTJS = "ReactJS"
  ANGULARJS = "AngularJS"
  VUEJS = "VueJS"
  REMIX = "Remix"
  NEXTJS = "NextJS"
  ASTRO = "Astro"
  NUXJS = "NuxtJS"
  NESTJS = "NestJS"
  EXPRESSJS = "ExpressJS"
  DJANGO = "Django"
  FLASK = "Flask"
  RUBY_ON_RAILS = "Ruby on Rails"
  SINATRA = "Sinatra"
  AQUEDUCT = "Aqueduct"
  VAPOR = "Vapor"
  KTOR = "Ktor"
  GIN = "Gin"
  ECHO = "Echo"
  DOTNET = ".NET"
  ASPNET_CORE = "ASP.NET Core"
  WXWIDGETS = "wxWidgets"
  ELECTRON = "Electron"
  NATIVE_ANDROID = "Native Android Development"
  NATIVE_IOS = "Native iOS Development"
  FLUTTER = "Flutter"
  REACT_NATIVE = "React Native"
  PANDAS = "Pandas"
  NUMPY = "NumPy"
  SCIPY = "SciPy"
  TENSORFLOW = "TensorFlow"
  PYTORCH = "PyTorch"
  SCIKIT_LEARN = "scikit-learn"
  UNREAL_ENGINE = "Unreal Engine"
  UNITY = "Unity"
